<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Photogallery extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
		$this->load->model('secure/Photogallery_model');
		
    } 

    /*
     * Listing of postlist
     */
    function index()
    {
        $per = $this->check_permission();
		
		
		if($per=='All'){
        $data['gallerylist'] = $this->Photogallery_model->get_all_gallerylist();
		}
		elseif($per=='Own'){
		$data['gallerylist'] = $this->Photogallery_model->get_own_gallerylist();
		}
		$data['categorylist'] = $this->Photogallery_model->get_gallery_categorylist();
		
		//var_dump($data['postlist']); exit;
		
		$this->render_template('secure/photogallery/index', $data);
    }
	
	function galleryCategoryList()
    {
        $per = $this->check_permission();
		
		
		if($per=='All'){
        $data['categorylist'] = $this->Photogallery_model->get_gallery_categorylist();
		}
		elseif($per=='Own'){
		$data['categorylist'] = $this->Photogallery_model->get_own_categorylist();
		}
		
		//var_dump($data);
		$this->render_template('secure/photogallery/GalleryCategoryList', $data);
    }
    /*
     * Adding a new post
     */
	 
	function addGalleryCategory(){
		$this->check_permission();
	   	
		
	   	$this->load->library('form_validation');
		$this->form_validation->set_rules('category_parent_id','Category','is_unique[tbl_category.category_title]|required');
		$this->form_validation->set_rules('category_title','Category Title','is_unique[tbl_category.category_title]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'display_in_menu' => $this->input->post('display_in_menu'),
				'category_parent_id' => $this->input->post('category_parent_id'),
				'category_title' => $this->input->post('category_title'),
				'status' => $this->input->post('status'),
				'createdby' => $this->session->userdata('id'),
				'createdon' => date_timestamp_get(date_create()),
            );
            
            $category_id = $this->Photogallery_model->insert_data('tbl_gallery_category',$params);
            if($category_id){
			$this->session->set_flashdata('msg', '<div class="alert alert-success">record Added!</div>');
			redirect('secure/photogallery/addGallerycategory');
			}
        }
        else
        {	
			$data['all_categorylist'] = $this->Photogallery_model->get_gallery_categorylist();
			$this->render_template('secure/photogallery/addGalleryCategory',$data);
        }
	}
	
	function editGalleryCategory($id){
		$data['gallery_category'] = $this->Photogallery_model->get_data('tbl_gallery_category', '*', array('id'=>$id));
        $per = $this->check_permission();
		
		
		if($per=='Own'){
		if(!$data['gallery_category']['createdby']==$this->session->userdata('id')){
			echo '<script> alert("Access Denied! You do not have permission to access this page");</script>';
			echo '<script> window.history.back();</script>';
		}
		}
        if(isset($data['gallery_category']['id']))
        {
	   	
		
	   	$this->load->library('form_validation');
		$this->form_validation->set_rules('category_parent_id','Category','required');
		$this->form_validation->set_rules('category_title','Category Title','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'display_in_menu' => $this->input->post('display_in_menu'),
				'category_parent_id' => $this->input->post('category_parent_id'),
				'category_title' => $this->input->post('category_title'),
				'status' => $this->input->post('status'),
				'createdby' => $this->session->userdata('id'),
				'createdon' => date_timestamp_get(date_create()),
            );
            
            $category_id = $this->Photogallery_model->update_data('tbl_gallery_category',$id,$params);
            if($category_id){
			$this->session->set_flashdata('msg', '<div class="alert alert-success">record Updated!</div>');
			redirect('secure/photogallery/gallerycategorylist');
			}
        }
        else
        {	$data['all_categorylist'] = $this->Photogallery_model->get_gallery_categorylist();
            
            
			$this->render_template('secure/photogallery/editGalleryCategory',$data);
        }
		}
		 else
            
			$this->session->set_flashdata('msg', '<div class="alert alert-danger">The category you are trying to edit does not exist.</div>');
	}
	 
    function add()
    {   
        $this->check_permission();
		$data['categorylist'] = $this->Photogallery_model->get_gallery_categorylist();
		
		//var_dump($data['categorylist']); exit;
		
		$this->load->library('form_validation');
		
		if($_FILES['upload_file']['name']!='')
		{$_POST['upload_file'] = $_FILES['upload_file'];
				
					$config['upload_path'] = 'uploads/gallery/';
					$config['allowed_types'] = 'jpg|png|jpeg';
					$config['max_size'] = '0';
					$config['max_filename'] = '255';
					$config['encrypt_name'] = TRUE;
									//$file = array();
									$is_file_error = FALSE;
									if (!$is_file_error) {
										$s =  $this->upload->initialize($config);
										if (!$this->upload->do_upload('upload_file'))
										{
											//$this->form_validation->set_rules('upload_type','Upload Type','required',$this->upload->display_errors());
									      $this->session->set_flashdata('msg', '<div class="alert alert-danger">'.$this->upload->display_errors().'</div>');
            							redirect('secure/photogallery/add');
										 // echo $this->upload->display_errors();
									      $is_file_error = TRUE;
						                }
									    else
										{
							               $file = $this->upload->data('file_name');
						                }
					            }	
							    
							}
		
		
		$this->form_validation->set_rules('image_title','Post Title','required');
		$this->form_validation->set_rules('category_id','Category','required|integer');
		$this->form_validation->set_rules('status','Status','required|integer');
		
		if($this->form_validation->run())     
        {   
				
				//var_dump($_POST);
            	$params = array(
				'image_title' => $this->input->post('image_title'),
				'category_id' => $this->input->post('category_id'),
				'upload_file' => $file,
				'status' => $this->input->post('status'),
				'createdby' => $this->session->userdata('id'),
				'createdon' => date_timestamp_get(date_create()),
            );
			//var_dump($params); exit;
            $user_id = $this->Photogallery_model->insert_data('tbl_gallery', $params);
			if($user_id){
				
				
			$this->session->set_flashdata('msg', '<div class="alert alert-success">record Added!</div>');
            redirect('secure/photogallery/index');
			}
        }
        else
        {            
            
			$this->render_template('secure/photogallery/addGallery',$data);
        }
    }  

    function editGallery($id)
    {   
        $data['categorylist'] = $this->Photogallery_model->get_gallery_categorylist();
		$data['post'] = $this->Photogallery_model->get_data('tbl_gallery', '*', array('id'=>$id));
        $per = $this->check_permission();
		
		
		if($per=='Own'){
		if(!$data['post']['createdby']==$this->session->userdata('id')){
			echo '<script> alert("Access Denied! You do not have permission to access this page");</script>';
			echo '<script> window.history.back();</script>';
		}
		}
        if(isset($data['post']['id']))
        {
		//var_dump($data['categorylist']); exit;
		
		$this->load->library('form_validation');
		
		if($_FILES['upload_file']['name']!='')
		{$_POST['upload_file'] = $_FILES['upload_file'];
				$this->form_validation->set_rules('upload_type','Upload Type','required');
				$config['upload_path'] = 'uploads/post/photo/';
					$config['allowed_types'] = 'jpg|png|jpeg';
					$config['max_size'] = '0';
									
									$config['max_filename'] = '255';
									$config['encrypt_name'] = TRUE;
									//$file = array();
									$is_file_error = FALSE;
									if (!$is_file_error) {
										$s =  $this->upload->initialize($config);
										if (!$this->upload->do_upload('upload_file'))
										{
											//$this->form_validation->set_rules('upload_type','Upload Type','required',$this->upload->display_errors());
									      $this->session->set_flashdata('msg', '<div class="alert alert-danger">'.$this->upload->display_errors().'</div>');
            							redirect('secure/photogallery/edit/'.$id);
										 // echo $this->upload->display_errors();
									      $is_file_error = TRUE;
						                }
									    else
										{
							               $file = $this->upload->data('file_name');
										   $params['upload_file'] = $file;
						                }
					            }	
							    
							}
		
		
		$this->form_validation->set_rules('image_title','Post Title','required');
		$this->form_validation->set_rules('category_id','Category','required|integer');
		$this->form_validation->set_rules('status','Status','required|integer');
		
		if($this->form_validation->run())     
        {   
				
				//var_dump($_POST);
            	$params = array(
				'image_title' => $this->input->post('image_title'),
				'status' => $this->input->post('status'),
				'createdby' => $this->session->userdata('id'),
				'createdon' => date_timestamp_get(date_create()),
            );
			//var_dump($params); exit;
            $update = $this->Photogallery_model->update_data('tbl_gallery', $id, $params);
			if($update){
			$this->session->set_flashdata('msg', '<div class="alert alert-success">record updated!</div>');
            redirect('secure/photogallery/index');
			}
        }
        else
        {            
            
			$this->render_template('secure/photogallery/editGallery',$data);
        }
		}
		else
		$this->session->set_flashdata('msg', '<div class="alert alert-danger">The post you are trying to edit does not exist.</div>');
    }  
    /*
     * Deleting post
     */
    function delete($id)
    {
        $post = $this->Photogallery_model->get_data('tbl_gallery','*',array('id'=>$id));
		$per = $this->check_permission();
		
		
		if($per=='Own'){
		if(!$post['createdby']==$this->session->userdata('id')){
			echo '<script> alert("Access Denied! You do not have permission to access this page");</script>';
			echo '<script> window.history.back();</script>';
		}
		}
		
        // check if the group exists before trying to delete it
        if(isset($post['id']))
        {	
			if($post['upload_file']!=''){
				$filepath = 'uploads/gallery/'.$post['upload_file'];
			}
			if(is_file($filepath)){
			unlink($filepath);
			}
			
            $this->Photogallery_model->delete_data('tbl_gallery',$id);
			$this->session->set_flashdata('msg', '<div class="alert alert-danger">Image Deleted!</div>');
            redirect('secure/photogallery/index');
        }
        else
            $this->session->set_flashdata('msg', '<div class="alert alert-danger">The group you are trying to delete does not exist.</div>');
    }
    
}
