<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Advertise_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get advertise by id
     */
    	function get_advertise($id)
    {
        return $this->db->get_where('tbl_advertise', array('id'=>$id))->row_array();
    }
        
    /*
     * Get all advertiselist
     */
    function get_all_advertiseslist()
    {
        
		$this->db->select('*');
		$this->db->from('tbl_advertise');
		$this->db->order_by('tbl_advertise.id', 'desc');
		$query = $this->db->get();
		return $query->result_array();
        
		
    }
      public function save_file_info($file, $where, $table, $field) {
		//start db traction
		$this->db->trans_start();
		
		$this->db->where($where);
		$this->db->update($table, array($field=>$file['file_name']));
		
		//complete the transaction
		$this->db->trans_complete();
		//check transaction status
		if ($this->db->trans_status() === FALSE) {
			$file_path = $file['full_path'];
			//delete the file from destination
			if (file_exists($file_path)) {
			unlink($file_path);
		}
		//rollback transaction
		$this->db->trans_rollback();
			return FALSE;
		} else {
			//commit the transaction
			$this->db->trans_commit();
			return TRUE;
		}
	}	
	 function get_own_advertiselist()
    {
        
			$this->db->select('*');
			$this->db->from('tbl_advertise');
			$this->db->where('tbl_advertise.createdby', $this->session->userdata('id'));
			$this->db->order_by('tbl_advertise.id', 'desc');
			$query = $this->db->get();
			return $query->row_array();
		
	}   
    /*
     * function to add new advertise
     */
    function add_advertise($params)
    {
        $this->db->insert('tbl_advertise',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update advertise
     */
    function update_advertise($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_advertise',$params);
    }
    
    /*
     * function to delete advertise
     */
    function delete_advertise($id)
    {
        
		return $this->db->delete('tbl_advertise',array('id'=>$id));
    }
}
