<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Post_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get data
     */
    	function get_data($table, $field, $where)
    {
        $this->db->select($field);	
		$this->db->from($table);
		$this->db->where($where);
		$query = $this->db->get();
		return $query->row_array();
    }
    
	/*
     * function to get post category list
     */
	 function get_post_categorylist()
    {
		$this->db->order_by('id', 'asc');
        return $this->db->get_where('tbl_post_category',array('status'=>1))->result_array();
    } 
	
	function get_own_categorylist()
    {
		$this->db->order_by('id', 'asc');
        return $this->db->get_where('tbl_post_category',array('status'=>1,'createdby', $this->session->userdata('id')))->result_array();
    }    
    /*
     * Get all userlist
     */
	 
    function get_all_postlist()
    {
        
		$this->db->select('tbl_post.*,tbl_post_category.category_title');
		$this->db->from('tbl_post');
		$this->db->join('tbl_post_category','tbl_post_category.id=tbl_post.category_id');
		$this->db->order_by('tbl_post.id', 'desc');
		$query = $this->db->get();
		return $query->result_array();
        
		
    }
      public function save_file_info($file, $where, $table, $field) {
		//start db traction
		$this->db->trans_start();
		
		$this->db->where($where);
		$this->db->update($table, array($field=>$file['file_name']));
		
		//complete the transaction
		$this->db->trans_complete();
		//check transaction status
		if ($this->db->trans_status() === FALSE) {
			$file_path = $file['full_path'];
			//delete the file from destination
			if (file_exists($file_path)) {
			unlink($file_path);
		}
		//rollback transaction
		$this->db->trans_rollback();
			return FALSE;
		} else {
			//commit the transaction
			$this->db->trans_commit();
			return TRUE;
		}
	}	
	 function get_own_postlist()
    {
        
			$this->db->select('*');
			$this->db->from('tbl_post');
			$this->db->join('tbl_post_category','tbl_post_category.id=tbl_post.category_id');
			$this->db->where('tbl_post.createdby', $this->session->userdata('id'));
			$this->db->order_by('tbl_post.id', 'desc');
			$query = $this->db->get();
			return $query->row_array();
		
	}   
    /*
     * function to add data
     */
    function insert_data($table, $params)
    {
        $this->db->insert($table, $params);
        return $this->db->insert_id();
    }
	
	
    
    /*
     * function to update data
     */
    function update_data($table, $id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update($table, $params);
    }
    
    /*
     * function to delete data
     */
    function delete_data($table, $id)
    {
        
		return $this->db->delete($table, array('id'=>$id));
    }
}
